# Generated by Django 5.1.2 on 2025-08-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_delivery_address_order_address_and_more'),
    ]

    operations = [
    ]
